"""Enhance UserProgress model with session tracking and completion fields

Revision ID: 558e1ca78fff
Revises: 3f309004a4b2
Create Date: 2025-08-19 20:05:38.679655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558e1ca78fff'
down_revision = '3f309004a4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sub_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['sub_titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromid', sa.Integer(), nullable=False),
    sa.Column('fromlang', sa.SmallInteger(), nullable=False),
    sa.Column('toid', sa.Integer(), nullable=False),
    sa.Column('tolang', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['fromid'], ['sub_titles.id'], ),
    sa.ForeignKeyConstraint(['fromlang'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['toid'], ['sub_titles.id'], ),
    sa.ForeignKeyConstraint(['tolang'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('native_language_id', sa.SmallInteger(), nullable=True),
    sa.Column('target_language_id', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['native_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_provider', 'oauth_id', name='unique_oauth_user')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('sub_link_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_link_id', sa.Integer(), nullable=False),
    sa.Column('link_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['sub_link_id'], ['sub_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sub_link_id', sa.Integer(), nullable=False),
    sa.Column('current_alignment_index', sa.Integer(), nullable=False),
    sa.Column('total_alignments_completed', sa.Integer(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sub_link_id'], ['sub_links.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sub_link_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.drop_table('sub_link_lines')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('sub_links')
    op.drop_table('sub_lines')
    op.drop_table('sub_titles')
    op.drop_table('languages')
    # ### end Alembic commands ###
